# This workflow uses the Actions Tagger action, which is a viable alternative to Latest Tag. 
# If you want to see an example on how to use Latest Tag, please check out the latest-tag.yml file in this directory.

name: Keep the major versions up-to-date

on:
  release:
    types: [published]

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
